### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by patriciachrysy** [patriciachrysy/html-capstone-project#2]
Feel free to leave a comment!

**Comment by Kyle-Law** [comment]
Great Job @patriciachrysy ! Here are my remarks:
- on the search page, items are not responsive across medium - large screen size as shown in pic below
![image](https://user-images.githubusercontent.com/55923773/74811950-83e9e900-532d-11ea-811e-72ec0e8412f0.png)
It could possibly solved by removing `grid: 150px repeat(3, 350px)/repeat(3, 350px);` of section class
![image](https://user-images.githubusercontent.com/55923773/74812206-01155e00-532e-11ea-904c-13496d8c859f.png)

- The 65% width of the search box shall be an easy fix. Just give them 65% on that particular media queries or below. 

- Commit more often especially when it's a 3-pages website. 

That's all from me :)

**Comment by dili021** [comment]
I don't see an h-scroll but I am getting this weird wrapping of the icons
![image](https://user-images.githubusercontent.com/55356496/74811195-47000100-52f1-11ea-8693-794868c3a36d.png)
I am getting a small h-scroll below 400px

here it is with 0 margin on the logo text and 35px font-size. Used -20% left on the animated img to reposition it. Add this just to the <768px.
![image](https://user-images.githubusercontent.com/55356496/74811852-a6aadc00-52f2-11ea-9328-df7333e4a911.png)
That's all we have time for :) I suggest you add this to a global css/sass file as it's causing issues on all the pages and use it via <link> if css or @import with sass/scss.

**Comment by patriciachrysy** [comment]
Thank you very much guys
